apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-services-ci-
spec:
  entrypoint: main
  activeDeadlineSeconds: 600
  volumes:
    - name: docker-credentials
      secret:
        secretName: docker-credentials
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: maven-repository
      persistentVolumeClaim:
        claimName: maven-repository-cache
  volumeClaimTemplates:
    - metadata:
        name: workspace
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 1Gi
  templates:
    - name: main
      steps:
        - - name: clone
            template: git-clone
        - - name: build
            template: maven-build
        - - name: cd
            template: update-cd-repo
    - name: git-clone
      container:
        image: alpine/git:v2.34.2
        volumeMounts:
          - name: workspace
            mountPath: /workspace
        command: [sh, -c]
        args: ["git clone https://github.com/omallo/hello-services.git /workspace"]
    - name: maven-build
      container:
        image: openjdk:17-alpine3.14
        volumeMounts:
          - name: maven-repository
            mountPath: /root/.m2
          - name: docker-credentials
            mountPath: /root/.docker
          - name: workspace
            mountPath: /workspace
        workingDir: /workspace
        command: [sh, -c]
        args: ["./mvnw clean package jib:build --batch-mode"]
    - name: update-cd-repo
      script:
        image: omallo/cicd-base:latest
        env:
          - name: GITHUB_TOKEN
            value:
        volumeMounts:
          - name: workspace
            mountPath: /workspace
        workingDir: /workspace
        command: [sh]
        source: |
          GIT_COMMIT=$(git log -1 --pretty=format:"%H")
          IMG_DIGEST=$(crane digest docker.io/omallo/hello-services)

          git config --global user.name "CICD"
          git config --global user.email "cicd@example.com"

          git clone https://unused:${GITHUB_TOKEN}@github.com/omallo/hello-services-cd.git /workspace-cd
          cd /workspace-cd/dev

          kustomize edit set image docker.io/omallo/hello-services=@$IMG_DIGEST

          kustomize edit remove resource "github.com/omallo/hello-services/src/main/kustomize/base*"
          kustomize edit add resource "github.com/omallo/hello-services/src/main/kustomize/base?ref=$GIT_COMMIT"

          git add -A
          git commit -m "update the deployment config for the dev environment"
          git push

          argocd login --insecure --grpc-web argocd-server.argocd.svc.cluster.local --username admin --password password
          argocd app sync hello-services-dev --timeout 120s
