apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-services-ci-
spec:
  entrypoint: main
  activeDeadlineSeconds: 600
  volumes:
    - name: docker-credentials
      secret:
        secretName: docker-credentials
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: maven-repository
      persistentVolumeClaim:
        claimName: maven-repository-cache
  volumeClaimTemplates:
    - metadata:
        name: workspace
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 1Gi
  templates:
    - name: main
      steps:
        - - name: clone
            template: git-clone
        - - name: build
            template: maven-build
    - name: git-clone
      container:
        image: alpine/git:v2.34.2
        volumeMounts:
          - name: workspace
            mountPath: /workspace
        command: [sh, -c]
        args: ["git clone https://github.com/omallo/hello-services.git /workspace"]
    - name: maven-build
      container:
        image: openjdk:17-alpine3.14
        volumeMounts:
          - name: maven-repository
            mountPath: /root/.m2
          - name: docker-credentials
            mountPath: /root/.docker
          - name: workspace
            mountPath: /workspace
        workingDir: /workspace
        command: [sh, -c]
        args: ["./mvnw clean package jib:build --batch-mode"]
    - name: kaniko-build
      container:
        image: gcr.io/kaniko-project/executor
        volumeMounts:
          - name: docker-credentials
            mountPath: /kaniko/.docker
          - name: workspace
            mountPath: /workspace
        args: ["--context=/workspace", "--destination=docker.io/omallo/hello-services"]
    - name: buildpacks-build
      container:
        image: paketobuildpacks/builder:base
        volumeMounts:
          - name: docker-credentials
            mountPath: /home/cnb/.docker
          - name: maven-repository
            mountPath: /home/cnb/.m2
          - name: workspace
            mountPath: /workspace
        command: [/cnb/lifecycle/creator]
        args: ["-app=/workspace", "docker.io/omallo/hello-services"]
