FROM alpine:3.16.0

RUN apk add --update-cache bash git jq yq curl docker-cli github-cli \
  && rm -rf /var/cache/apk/* \
  && curl -sSL "https://storage.googleapis.com/kubernetes-release/release/v1.24.1/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl \
  && chmod +x /usr/local/bin/kubectl \
  && (curl -sSL "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.5.5/kustomize_v4.5.5_linux_amd64.tar.gz" | tar xzf - -C /usr/local/bin kustomize) \
  && (curl -sSL "https://github.com/google/go-containerregistry/releases/download/v0.9.0/go-containerregistry_Linux_x86_64.tar.gz" | tar xzf - -C /usr/local/bin crane) \
  && curl -sSL "https://github.com/argoproj/argo-cd/releases/download/v2.4.0/argocd-linux-amd64" -o /usr/local/bin/argocd \
  && chmod +x /usr/local/bin/argocd
