apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: hello-
commonLabels:
  app: hello
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: cm-env
    literals:
      - GREETING=Hello from ENV
  - name: cm-vol
    literals:
      - |
        application.yaml=
        greeting: Hello from VOL
        spring.config.import: optional:configtree:/app/secrets/
replicas:
  - name: dpl
    count: 1
images:
  - name: dpl-img
    newName: docker.io/omallo/hello-services
    newTag: latest
