apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: hello-services-
commonLabels:
  app: hello-services
images:
  - name: dpl-img
    newName: docker.io/omallo/hello-services
    newTag: latest
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
generatorOptions:
  immutable: true
configMapGenerator:
  - name: cm-env
    literals:
      - HELLO_GREETING=Hello from ENV
  - name: cm-vol
    literals:
      - |
        application.yaml=
        hello.greeting: Hello from VOL
secretGenerator:
  - name: sec-vol
    literals:
      - hello.secret=s3cr3t-from-vol
replicas:
  - name: dpl
    count: 1
