apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-local
resources:
  - ../base
generatorOptions:
  immutable: true
configMapGenerator:
  - name: hello-services-cm-env
    behavior: merge
    envs:
      - config.env
secretGenerator:
  - name: hello-services-sec-env
    behavior: merge
    envs:
      - secrets.env
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: hello-services-ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: hello-services-local.192.168.64.38.nip.io
replicas:
  - name: hello-services-dpl
    count: 1
